<a href="https://colab.research.google.com/github/badalmehta2004/badalmehta2004/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1=np.array([1,2,3,4]) # 1 1 d array
a2=np.array([[1,2,3,4],[5,6,7,8]]) # 2d array list of multiple 1d array
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3d array multiple 2d array
print(a1)
print(a2)
print(a3)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# default values
# np.zeros(shape)
a4=np.zeros(4) # 1 d
print(a4)
a5=np.zeros((2,3)) # 2d
print(a5)

# note if array toh homogenous data hi store kargea \
# if multiple datatypes denge toh jo superior datatype hoga vo hoga array a dataype
# np.ones(shape)

a4=np.ones(4,dtype='i4') #
print(a4)
a5=np.ones((2,3)) # 2d
a5
a4.dtype

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 1 1 1]


dtype('int32')

In [ ]:
# specific value
#np.full(shape,value)
a6=np.full(4,10)
print(a6)

a7=np.full((3,4),5) # 3 X 4 matrix and each value is 5
print(a7)

a7=np.full((3,4,2),5) # 3 X 4 matrix and each value is 5
print(a7)

[10 10 10 10]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[[5 5]
  [5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]
  [5 5]]]


In [ ]:
# identity matrix
#np.eye(size) # alaways square matrix

idetity_matrix=np.eye(4)
print(idetity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# sequence of numbers
# arange(start,end,step) returns numpy array same as range() which return list
a9=np.arange(1,11)
print(a9)
a9=np.arange(0,11,2) # even number
print(a9)


[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [ ]:
# properties of numpy array
# shape rows,cols
#array_name.attribute
print(a1.shape)
print(a2.shape)
print(a3.shape)

# size # number of elements

print(a1.size)
print(a2.size)
print(a3.size)

# ndim
# number of dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

(4,)
(2, 4)
(2, 2, 2)
4
8
8
1
2
3


In [ ]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
# a1.dtype='float32' # changed the datatype of a1 to float 32
# print(a1)

# change dtype
#.astype(new_dtype)
new_a1=a1.astype(float)
print(new_a1)
print(new_a1.dtype)

int64
int64
int64
[1. 2. 3. 4.]
float64


In [ ]:
# maths opertaions har ek element pe ho jayega
a10=np.array([10,20,30,40,50,60,70])
print(a10+5)
print(a10-5)
print(a10*2)
print(a10/2)
print(a10**3)
print(a10//4)
print(a10%3)
# print(a1+a10)
print(a1)
print(a10)
# print(a1*a10) # not matrix multiplcation its corresponding element multiplication

[15 25 35 45 55 65 75]
[ 5 15 25 35 45 55 65]
[ 20  40  60  80 100 120 140]
[ 5. 10. 15. 20. 25. 30. 35.]
[  1000   8000  27000  64000 125000 216000 343000]
[ 2  5  7 10 12 15 17]
[1 2 0 1 2 0 1]
[1 2 3 4]
[10 20 30 40 50 60 70]


In [ ]:
# matrix mul
a11=np.array([[1,2],[3,4],[5,6]]) # 3 X 2
a12=np.array([[1,2,3],[4,5,6]])  # 2 X 3
print(a11@a12) # @ sign is used for matrix multiplication
print(np.matmul(a11,a12)) # matmul method

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
# agreegation functions
print(a10)
print(np.sum(a10))
print(np.mean(a10))
print(np.min(a10))
print(np.max(a10))
print(np.std(a10))
print(np.var(a10))

[10 20 30 40 50 60 70]
280
40.0
10
70
20.0
400.0


In [ ]:
#indexing
print(a10)
print(a10[0]) # ist element
print(a10[-1]) # last element
print(a10[1]) # 2nd element
print(a10[-2]) # second last element

[10 20 30 40 50 60 70]
10
70
20
60


In [ ]:
# slicing
# array[start,end,step] step has direction and jump that is step by default right direction and step=1

# whole array
print(a10[0::])
# every 2nd element\
print(a10[0::2])
#revrese
print(a10[::-1])
# any middle values
print(a10[1:4])

[10 20 30 40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]
[20 30 40]


In [ ]:
# fancy indexing
# selecting multiple indexes at once
print(a10[[1,4,6]]) # we give list of indexes in index field
# creates duplicate array of indexs given

[20 50 70]


In [ ]:
# booklean indexing
# condition on rows
print(a10[a10>30]) # all values greater than 30
print(a10[a10>25]) # all values greater than 25

[40 50 60 70]
[30 40 50 60 70]


In [ ]:
#reshaping and manipulating arrays
#reshaping change dimesion of array without modify data 1D ->2D 2D ->3D
# rehaping returns the view of original array  not copy changing in reshaped array also affects original array
print(a10)
reshaped_a10=a10.reshape(7,1)
print(reshaped_a10)
a13=np.array([1,2,3,4,5,6])
a13_reshaped=a13.reshape(3,2)
print(a13_reshaped)
a13_reshaped[1][1]=50 # changed in reshaped array
print(a13_reshaped)
print(a13.reshape(2,3))
print(a13) # 50 is also reflected in original array


[10 20 30 40 50 60 70]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1  2]
 [ 3 50]
 [ 5  6]]
[[ 1  2  3]
 [50  5  6]]
[ 1  2  3 50  5  6]


In [ ]:
# flattening array
# multidimension to 1D

# 1 flatten array retuns copy chnaging value Does not affect original array
#.flatten()
# a13_reshaped_flat=a13_reshaped.flatten()
# print(a13_reshaped_flat)
# a13_reshaped_flat[1]=100 # changed in flatten array
# print(a13_reshaped_flat)
# print(a13) # does not affect original array


# .ravel()
#ravel  retuns view chnaging value Does affect original array
a13_reshaped_flat=a13_reshaped.ravel()
print(a13_reshaped_flat)
a13_reshaped_flat[1]=100 # changed in flatten array
print(a13_reshaped_flat)
print(a13) # also reflected in original array


[ 1  2  3 50  5  6]
[  1 100   3  50   5   6]
[  1 100   3  50   5   6]


In [ ]:
# operatiions on elements

# np.insert(original_array,index,axis)
# axis=none inserted in flatted version of array
# axis=0 inserted row wise
#axis=1 inserted colomun wise
print(a13)
new_a13=np.insert(a13,1,102,axis=None) # retuns another array with updated value no change in original array
print(f"original array: {a13}")
print(f"another updated array: {new_a13}")
print(len(a13))

# 2d array
print(f"original array: {a13_reshaped}")
arr1=np.insert(a13_reshaped,1,[102,110],axis=0) # row wise
print(f"another updated array(row wise):\n {arr1}")
arr1=np.insert(a13_reshaped,1,[102,110,129],axis=1) # col wise
print(f"another updated array(col wise):\n {arr1}")





[  1 100   3  50   5   6]
original array: [  1 100   3  50   5   6]
another updated array: [  1 102 100   3  50   5   6]
6
original array: [[  1 100]
 [  3  50]
 [  5   6]]
another updated array(row wise):
 [[  1 100]
 [102 110]
 [  3  50]
 [  5   6]]
another updated array(col wise):
 [[  1 102 100]
 [  3 110  50]
 [  5 129   6]]


In [ ]:
 #np.append(original_array,index,axis)
# axis=none appended in flatted version of array
# axis=0 appended row wise
#axis=1 appended colomun wise
#Append karte waqt arrays ki dimensions same aur shape compatible honi chahiye.


print(a13)
new_a13=np.append(a13,102,axis=None) # retuns another array with updated value no change in original array
print(f"original array: {a13}")
print(f"another updated array: {new_a13}")

# 2d array
print(f"original array: {a13_reshaped}")
arr1=np.append(a13_reshaped,[[102,110]],axis=0) # row wise
print(f"another updated array(row wise):\n {arr1}")
arr1=np.append(a13_reshaped,[[102],
                             [110],
                              [129]],axis=1) # col wise
print(f"another updated array(col wise):\n {arr1}")

[  1 100   3  50   5   6]
original array: [  1 100   3  50   5   6]
another updated array: [  1 100   3  50   5   6 102]
original array: [[  1 100]
 [  3  50]
 [  5   6]]
another updated array(row wise):
 [[  1 100]
 [  3  50]
 [  5   6]
 [102 110]]
another updated array(col wise):
 [[  1 100 102]
 [  3  50 110]
 [  5   6 129]]


In [ ]:
# concatenate
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2))
print(a3)
a3=np.concatenate((a1,a2),axis=0)
print(a3)
a1=np.array([[1,2],[3,4]])
a2=np.array([[4,5],[6,7]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)





[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 4 5]
 [3 4 6 7]]


In [ ]:
# stacking
# ''' vstack((arr1,arr2)) row wise
# hstack() col wise'''

a1=np.array([1,2,3,4])
a2=np.array([4,6,8,20])

print(np.vstack((a1,a2))) # vertically
print(np.hstack((a1,a2))) # horizontally

# 2d array
a1=np.array([[1,2],[3,4]])
a2=np.array([[4,6],[8,20]])
print(np.vstack((a1,a2))) # vertically
print(np.hstack((a1,a2))) # horizontally

[[ 1  2  3  4]
 [ 4  6  8 20]]
[ 1  2  3  4  4  6  8 20]
[[ 1  2]
 [ 3  4]
 [ 4  6]
 [ 8 20]]
[[ 1  2  4  6]
 [ 3  4  8 20]]


In [ ]:
# splitting
"""
equal splitting
np.split(arr,split_size)
 np.hsplit() # col wise
 np.vsplit()
"""

a1=np.array([1,2,3,4,4,6,8,20])
print(np.split(a1,2))

a1=np.array([[1,2],[3,4],[4,6],[8,20]])
print(a1)
print(np.vsplit(a1,2)) # vertically
print(np.hsplit(a1,2))

[array([1, 2, 3, 4]), array([ 4,  6,  8, 20])]
[[ 1  2]
 [ 3  4]
 [ 4  6]
 [ 8 20]]
[array([[1, 2],
       [3, 4]]), array([[ 4,  6],
       [ 8, 20]])]
[array([[1],
       [3],
       [4],
       [8]]), array([[ 2],
       [ 4],
       [ 6],
       [20]])]
